name: Build Android APK (PWABuilder)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Android APK
        uses: pwa-builder/pwa-action@v1
        with:
          # L'URL de votre PWA déjà déployée sur GitHub Pages
          url: https://andryraveloarison.github.io/cantique/
          # Identifiant de votre application
          packageId: com.andry.cantique
          # Nom de l'application
          name: Cantiques FFPM
          # On demande spécifiquement le build Android
          platform: android
          # Vous pourrez télécharger l'APK dans les artefacts
